version: '3.8'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./logs/:/usr/src/app/logs/
      - ./db/:/usr/src/app/db/
    ports:
      - 8000:8000
    env_file:
      - ./dev.env
